### ISSUE TITLE
Return object instead of array

### ISSUE THREAD

**Issue by aggunawan** [promopult/tiktok-marketing-api#2]
Hi, first of all thank you for the great sdk for TikTok Marketing API.

Instead return an array on api request call. Based on this [SDK](facebook/facebook-php-business-sdk) why not use object, eg. Objects\Advertiser instead of array ?

I want to contribute to your repo, cause i often work with couple ads provider. Instead of build one, why not build it together.

**Comment by gladyshev** [comment]
Thanks for appreciating our SDK. For our purposes, an array response is the most convenient. Objects like facebook's  require a lot of code to write and do nothing useful for us. It also breaks bс and requires to change the client code. Maybe in the future we'll rethink this approach and use objects.

However, if you would like to contribute to our repository we will be very grateful to you.
