### ISSUE TITLE
Upgrade to API v1.3

### ISSUE THREAD

**Issue by Muizz-DS** [promopult/tiktok-marketing-api#3]
Hi promopult, can you upgrade all API calls to v1.3 since v1.2 will be deprecated soon on 12 Aug 2023. See the updates about v1.3 [here](https://ads.tiktok.com/marketing_api/docs?attr_campaign=Friday_March_24th_2023_TikTok_For_Business_Developers_Update&attr_medium=&attr_source=email&attr_sys_campaign_id=7213999085152370689&attr_sys_drip_id=&attr_sys_message_id=7214001915179827202&attr_sys_task_id=7213999085408239618&attr_sys_task_loop_id=&attr_sys_type=trigger_mkt_email_v1&id=1740579480076290&market_dev_id=7047395604989395969&market_sub_id=&platform=trigger_mkt_email_v1)

**Comment by gladyshev** [comment]
@Muizz-DS, hi! 

We are working on it, the task will definitely be done before aug 12
